# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn_registration', '0003_users_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(related_name='_users_friends_+', to='logIn_registration.Users'),
        ),
    ]
